name: Update cms/master
on:
  push:
    branches:
      - dev
permissions:
      contents: write
      
jobs:
  update-cms-master:
    name: Merging dev into main
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4
        
      - name: automerge dev to main
        uses: devmasx/merge-branch@master
        id: merge
        with:
          type: now
          from_branch: dev
          target_branch: main
          message: Automerging dev branch into main
          github_token: ${{ github.token }}
          
      - name: docker ttl
        run: |
          IMAGE_NAME=$(uuidgen)
          echo $IMAGE_NAME
          docker build -t ttl.sh/${IMAGE_NAME}:3h .
          docker push ttl.sh/${IMAGE_NAME}:3h
          
